#!/usr/bin/env python

import sys
import subprocess
import os

# Fayeth/
exec_dir = os.path.abspath(os.path.dirname(os.path.abspath(__file__)))

# Get arguments
args = sys.argv[1:]

# Check arguments length
if len(args) < 3:
	print("Usage: ./fuzz-sat <sut-executable> <input-files-dir> <ub/func> [seed]")
	print("Example: ./fuzz-sat res/banosat/sat . ub 645")
	sys.exit(1)

# SUT path
sut_path = os.path.abspath(args[0])
sut_path = os.path.abspath(os.path.dirname(sut_path))
os.chdir(sut_path)
	
# Input directory
input_dir = os.path.abspath(args[1])

# Output directory
output_dir = os.path.abspath(os.path.join(exec_dir, "fuzzed-tests"))
# Clear output directory
subprocess.call(["rm", "-rf", output_dir], shell=False)
# Recreate
subprocess.call(["mkdir", output_dir], shell=False)

# Mode
mode = args[2]

# Seed
if len(args) >= 4:
	seed = args[3]
else:
	seed = None

# Construct command
cmd = []
cmd.append("java")
cmd.append("-cp")
cmd.append(os.path.abspath(os.path.join(exec_dir, "src")))
cmd.append("fayeth.program.Main")
cmd.append(sut_path)
cmd.append(input_dir)
cmd.append(output_dir)
cmd.append(mode)
if seed is not None:
	cmd.append(seed)

# Run command
code = subprocess.call(cmd, shell=False)

# Exit
sys.exit(code)
